"""Tests for the PostgreSQL schema design module.

No psycopg installation and no running PostgreSQL server are required.
These tests verify the DDL strings are structurally correct and carry
the right Postgres-specific types, without executing anything.
"""

from __future__ import annotations

import sys


class TestModuleImport:
    def test_imports_without_psycopg(self):
        # Remove psycopg from sys.modules to simulate it being absent, then
        # confirm the schema module still imports cleanly.
        import importlib

        # Unload cached module if present so we get a fresh import.
        mod_name = "kb_audit.storage.schema_postgres"
        sys.modules.pop(mod_name, None)

        # Patch psycopg out of sight.
        original = sys.modules.get("psycopg", None)
        sys.modules["psycopg"] = None  # type: ignore[assignment]
        try:
            mod = importlib.import_module(mod_name)
            assert mod is not None
        finally:
            if original is None:
                sys.modules.pop("psycopg", None)
            else:
                sys.modules["psycopg"] = original

    def test_no_psycopg_import_in_module(self):
        import ast
        import pathlib

        src = pathlib.Path("src/kb_audit/storage/schema_postgres.py").read_text()
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    assert alias.name != "psycopg", "schema_postgres.py must not import psycopg"
            elif isinstance(node, ast.ImportFrom):
                assert node.module != "psycopg", "schema_postgres.py must not import from psycopg"


class TestIterPostgresSchemaStatements:
    def test_returns_tuple(self):
        from kb_audit.storage.schema_postgres import iter_postgres_schema_statements

        result = iter_postgres_schema_statements()
        assert isinstance(result, tuple)

    def test_returns_nonempty_tuple_of_strings(self):
        from kb_audit.storage.schema_postgres import iter_postgres_schema_statements

        result = iter_postgres_schema_statements()
        assert len(result) > 0
        for stmt in result:
            assert isinstance(stmt, str)
            assert stmt.strip()

    def test_includes_all_table_and_index_statements(self):
        from kb_audit.storage.schema_postgres import (
            POSTGRES_INDEX_STATEMENTS,
            POSTGRES_SCHEMA_STATEMENTS,
            iter_postgres_schema_statements,
        )

        all_stmts = iter_postgres_schema_statements()
        for stmt in POSTGRES_SCHEMA_STATEMENTS:
            assert stmt in all_stmts
        for stmt in POSTGRES_INDEX_STATEMENTS:
            assert stmt in all_stmts

    def test_seed_sql_included(self):
        from kb_audit.storage.schema_postgres import (
            POSTGRES_SCAN_STATE_SEED_SQL,
            iter_postgres_schema_statements,
        )

        assert POSTGRES_SCAN_STATE_SEED_SQL in iter_postgres_schema_statements()


class TestRequiredTableNames:
    def test_scans_table(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "scans" in POSTGRES_SCHEMA_SQL

    def test_documents_table(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "documents" in POSTGRES_SCHEMA_SQL

    def test_audit_results_table(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "audit_results" in POSTGRES_SCHEMA_SQL

    def test_finding_workflow_table(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "finding_workflow" in POSTGRES_SCHEMA_SQL

    def test_scan_state_table(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "scan_state" in POSTGRES_SCHEMA_SQL


class TestPostgresSpecificTypes:
    def test_jsonb_present(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "JSONB" in POSTGRES_SCHEMA_SQL

    def test_timestamptz_present(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "TIMESTAMPTZ" in POSTGRES_SCHEMA_SQL

    def test_boolean_present(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "BOOLEAN" in POSTGRES_SCHEMA_SQL

    def test_identity_or_bigserial_present(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        has_identity = "GENERATED BY DEFAULT AS IDENTITY" in POSTGRES_SCHEMA_SQL
        has_bigserial = "BIGSERIAL" in POSTGRES_SCHEMA_SQL
        assert has_identity or has_bigserial, (
            "Expected BIGSERIAL or GENERATED BY DEFAULT AS IDENTITY for auto-increment PKs"
        )

    def test_jsonb_used_for_signals(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        audit_results_ddl = next(
            s for s in POSTGRES_SCHEMA_STATEMENTS if "audit_results" in s
        )
        assert "signals" in audit_results_ddl
        assert "JSONB" in audit_results_ddl

    def test_jsonb_used_for_trust_data(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        audit_results_ddl = next(
            s for s in POSTGRES_SCHEMA_STATEMENTS if "audit_results" in s
        )
        assert "trust_data" in audit_results_ddl
        assert "JSONB" in audit_results_ddl

    def test_jsonb_used_for_metadata(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        documents_ddl = next(
            s for s in POSTGRES_SCHEMA_STATEMENTS if "documents" in s
        )
        assert "metadata" in documents_ddl
        assert "JSONB" in documents_ddl

    def test_timestamptz_on_scans(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        scans_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "scans" in s)
        assert "TIMESTAMPTZ" in scans_ddl

    def test_boolean_on_scan_state(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        scan_state_ddl = next(
            s for s in POSTGRES_SCHEMA_STATEMENTS if "scan_state" in s
        )
        assert "BOOLEAN" in scan_state_ddl


class TestScanStateSeed:
    def test_seed_sql_is_string(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCAN_STATE_SEED_SQL

        assert isinstance(POSTGRES_SCAN_STATE_SEED_SQL, str)
        assert POSTGRES_SCAN_STATE_SEED_SQL.strip()

    def test_seed_targets_scan_state(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCAN_STATE_SEED_SQL

        assert "scan_state" in POSTGRES_SCAN_STATE_SEED_SQL

    def test_seed_uses_on_conflict_do_nothing(self):
        # Must be idempotent; SQLite uses INSERT OR IGNORE, Postgres uses ON CONFLICT.
        from kb_audit.storage.schema_postgres import POSTGRES_SCAN_STATE_SEED_SQL

        assert "ON CONFLICT" in POSTGRES_SCAN_STATE_SEED_SQL

    def test_seed_inserts_singleton_id_1(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCAN_STATE_SEED_SQL

        assert "1" in POSTGRES_SCAN_STATE_SEED_SQL


class TestConstraints:
    def test_scans_has_primary_key(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        scans_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "scans" in s)
        assert "PRIMARY KEY" in scans_ddl

    def test_documents_has_composite_primary_key(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        docs_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "documents" in s)
        assert "PRIMARY KEY" in docs_ddl
        # Composite: (id, scan_id)
        assert "scan_id" in docs_ddl

    def test_audit_results_has_composite_primary_key(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        ar_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "audit_results" in s)
        assert "PRIMARY KEY" in ar_ddl
        assert "document_id" in ar_ddl
        assert "scan_id" in ar_ddl

    def test_finding_workflow_has_primary_key_on_finding_key(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        fw_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "finding_workflow" in s)
        assert "finding_key" in fw_ddl
        assert "PRIMARY KEY" in fw_ddl

    def test_scan_state_singleton_check_constraint(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_STATEMENTS

        ss_ddl = next(s for s in POSTGRES_SCHEMA_STATEMENTS if "scan_state" in s)
        assert "CHECK" in ss_ddl
        assert "id = 1" in ss_ddl or "id=1" in ss_ddl


class TestIndexes:
    def test_index_on_scans_status(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        scans_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "scans" in s]
        assert any("status" in s for s in scans_indexes)

    def test_index_on_documents_scan_id(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        doc_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "documents" in s]
        assert any("scan_id" in s for s in doc_indexes)

    def test_index_on_audit_results_scan_id(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        ar_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "audit_results" in s]
        assert any("scan_id" in s for s in ar_indexes)

    def test_index_on_finding_workflow_state(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        fw_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "finding_workflow" in s]
        assert any("workflow_state" in s for s in fw_indexes)

    def test_index_on_finding_workflow_document_source(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        fw_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "finding_workflow" in s]
        assert any("document_id" in s for s in fw_indexes)

    def test_index_on_finding_workflow_last_seen(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        fw_indexes = [s for s in POSTGRES_INDEX_STATEMENTS if "finding_workflow" in s]
        assert any("last_seen_scan_id" in s for s in fw_indexes)

    def test_index_count_is_reasonable(self):
        from kb_audit.storage.schema_postgres import POSTGRES_INDEX_STATEMENTS

        # Should have several meaningful indexes, not zero or one
        assert len(POSTGRES_INDEX_STATEMENTS) >= 5


class TestNoSQLiteSyntax:
    def test_no_autoincrement(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "AUTOINCREMENT" not in POSTGRES_SCHEMA_SQL

    def test_no_insert_or_replace(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "INSERT OR REPLACE" not in POSTGRES_SCHEMA_SQL

    def test_no_pragma(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "PRAGMA" not in POSTGRES_SCHEMA_SQL

    def test_no_sqlite_sequence(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "sqlite_sequence" not in POSTGRES_SCHEMA_SQL

    def test_no_begin_immediate(self):
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "BEGIN IMMEDIATE" not in POSTGRES_SCHEMA_SQL

    def test_no_insert_or_ignore(self):
        # SQLite-specific form; Postgres uses ON CONFLICT DO NOTHING
        from kb_audit.storage.schema_postgres import POSTGRES_SCHEMA_SQL

        assert "INSERT OR IGNORE" not in POSTGRES_SCHEMA_SQL


class TestRenderPostgresSchemaSQL:
    def test_returns_string(self):
        from kb_audit.storage.schema_postgres import render_postgres_schema_sql

        result = render_postgres_schema_sql()
        assert isinstance(result, str)

    def test_matches_postgres_schema_sql_constant(self):
        from kb_audit.storage.schema_postgres import (
            POSTGRES_SCHEMA_SQL,
            render_postgres_schema_sql,
        )

        assert render_postgres_schema_sql() == POSTGRES_SCHEMA_SQL

    def test_contains_all_tables(self):
        from kb_audit.storage.schema_postgres import render_postgres_schema_sql

        sql = render_postgres_schema_sql()
        for table in ("scans", "documents", "audit_results", "finding_workflow", "scan_state"):
            assert table in sql
