"""PostgreSQL schema design for kb_audit.

This module contains the PostgreSQL DDL that the opt-in ``PostgresStorage``
backend applies on direct connect.  It is intentionally **non-executing** by
itself — nothing here imports psycopg or opens a connection.

Status
------
- Driver probe added: ``storage/postgres_support.py`` (Step 1)
- Schema design: this module (Step 2)
- ``PostgresStorage`` implementation: complete surface (Steps 3–7) —
  implements connection lifecycle, scan lease/lifecycle, document/result
  persistence, workflow persistence, scan history/diff, and maintenance;
  has opt-in live conformance tests (Step 8, ``KB_AUDIT_POSTGRES_TEST_URL``)
- Alembic migration added: ``migrations/versions/0001_initial_schema.py``
  (Step 9) — reuses ``iter_postgres_schema_statements()`` as single source
  of truth; apply with ``KB_AUDIT_POSTGRES_URL=<url> alembic upgrade head``
- ``create_storage()`` wiring: **done** (Step 10) — returns ``PostgresStorage``
  for ``postgres://`` and ``postgresql://`` URLs
- Live Postgres conformance against CI: **not done**

Design notes
------------
- Timestamps use ``TIMESTAMPTZ`` so that lease and snooze comparisons carry
  correct timezone semantics (unlike SQLite's plain ISO text strings).
- JSON-ish blobs use ``JSONB`` for efficient storage and future indexed queries.
- Scan/document IDs use ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` (SQL-standard
  syntax supported by Postgres 10+) instead of SQLite's ``AUTOINCREMENT``.
- Upserts will use ``INSERT ... ON CONFLICT DO UPDATE`` instead of
  SQLite's ``INSERT OR REPLACE``.
- The ``scan_state`` singleton is enforced by ``CHECK (id = 1)`` (same
  pattern as SQLite; valid Postgres syntax).
- ``ON DELETE CASCADE`` on foreign keys replaces the explicit ``DELETE FROM``
  statements used in the SQLite path when a scan is abandoned or failed.
- No tenant columns are included here; tenancy is a future hosted step.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Table DDL
# ---------------------------------------------------------------------------

_SCANS_DDL = """\
CREATE TABLE IF NOT EXISTS scans (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at     TIMESTAMPTZ NOT NULL,
    finished_at    TIMESTAMPTZ,
    document_count INTEGER     NOT NULL DEFAULT 0,
    status         TEXT        NOT NULL DEFAULT 'completed',
    owner_token    TEXT,
    error          TEXT
)"""

_DOCUMENTS_DDL = """\
CREATE TABLE IF NOT EXISTS documents (
    id            TEXT   NOT NULL,
    scan_id       BIGINT NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
    title         TEXT   NOT NULL,
    content_hash  TEXT   NOT NULL,
    source_type   TEXT   NOT NULL,
    url           TEXT,
    last_modified TIMESTAMPTZ,
    metadata      JSONB  NOT NULL DEFAULT '{}',
    PRIMARY KEY (id, scan_id)
)"""

_AUDIT_RESULTS_DDL = """\
CREATE TABLE IF NOT EXISTS audit_results (
    document_id             TEXT             NOT NULL,
    scan_id                 BIGINT           NOT NULL,
    overall_status          TEXT             NOT NULL,
    signals                 JSONB            NOT NULL DEFAULT '[]',
    suggested_replacement_id TEXT,
    confidence              DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    confidence_reason       TEXT             NOT NULL DEFAULT '',
    trust_data              JSONB            NOT NULL DEFAULT '{}',
    PRIMARY KEY (document_id, scan_id),
    FOREIGN KEY (document_id, scan_id)
        REFERENCES documents(id, scan_id) ON DELETE CASCADE
)"""

_FINDING_WORKFLOW_DDL = """\
CREATE TABLE IF NOT EXISTS finding_workflow (
    finding_key          TEXT        PRIMARY KEY,
    document_id          TEXT        NOT NULL,
    source_type          TEXT        NOT NULL,
    title                TEXT        NOT NULL,
    workflow_state       TEXT        NOT NULL DEFAULT 'open',
    note                 TEXT        NOT NULL DEFAULT '',
    assigned_owner       TEXT        NOT NULL DEFAULT '',
    due_date             TEXT,
    snoozed_until        TIMESTAMPTZ,
    dismissal_reason     TEXT        NOT NULL DEFAULT '',
    evidence_hash        TEXT        NOT NULL,
    first_seen_scan_id   BIGINT,
    last_seen_scan_id    BIGINT,
    last_checked_scan_id BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL
)"""

# Singleton table: the CHECK constraint limits the table to exactly one row
# with id = 1, mirroring the SQLite approach.  ``in_progress`` is a native
# BOOLEAN (not an INTEGER 0/1 as in SQLite), and ``lease_expires_at`` is a
# proper TIMESTAMPTZ for direct timestamp comparisons.
_SCAN_STATE_DDL = """\
CREATE TABLE IF NOT EXISTS scan_state (
    id              INTEGER     PRIMARY KEY CHECK (id = 1),
    in_progress     BOOLEAN     NOT NULL DEFAULT FALSE,
    last_scan_id    BIGINT,
    scan_error      TEXT,
    owner_token     TEXT,
    lease_expires_at TIMESTAMPTZ
)"""

# ---------------------------------------------------------------------------
# Index DDL
# ---------------------------------------------------------------------------

# Scan history: WHERE status='completed' ORDER BY id DESC LIMIT n
_IDX_SCANS_STATUS_ID = (
    "CREATE INDEX IF NOT EXISTS idx_scans_status_id "
    "ON scans(status, id DESC)"
)

# Scan-scoped document lookups (PK is (id, scan_id); scan-only needs this)
_IDX_DOCUMENTS_SCAN_ID = (
    "CREATE INDEX IF NOT EXISTS idx_documents_scan_id "
    "ON documents(scan_id)"
)

# Scan-scoped result lookups (PK is (document_id, scan_id); scan-only path)
_IDX_AUDIT_RESULTS_SCAN_ID = (
    "CREATE INDEX IF NOT EXISTS idx_audit_results_scan_id "
    "ON audit_results(scan_id)"
)

# Document-centric result lookups (carry-forward, per-doc history)
_IDX_AUDIT_RESULTS_DOCUMENT_ID = (
    "CREATE INDEX IF NOT EXISTS idx_audit_results_document_id "
    "ON audit_results(document_id)"
)

# Workflow queue filter (default queue, include_all toggle)
_IDX_FINDING_WORKFLOW_STATE = (
    "CREATE INDEX IF NOT EXISTS idx_finding_workflow_state "
    "ON finding_workflow(workflow_state)"
)

# Auto-fix and finding-key derivation: filter by document/source identity
_IDX_FINDING_WORKFLOW_DOC_SOURCE = (
    "CREATE INDEX IF NOT EXISTS idx_finding_workflow_document_source "
    "ON finding_workflow(document_id, source_type)"
)

# Auto-fix: scanned_doc_ids check uses last_seen_scan_id
_IDX_FINDING_WORKFLOW_LAST_SEEN = (
    "CREATE INDEX IF NOT EXISTS idx_finding_workflow_last_seen "
    "ON finding_workflow(last_seen_scan_id)"
)

# Carry-forward tracking: distinguish re-analyzed vs. carried-forward results
_IDX_FINDING_WORKFLOW_LAST_CHECKED = (
    "CREATE INDEX IF NOT EXISTS idx_finding_workflow_last_checked "
    "ON finding_workflow(last_checked_scan_id)"
)

# ---------------------------------------------------------------------------
# Singleton seed SQL
# ---------------------------------------------------------------------------

#: Insert the single scan_state row on first schema apply.
#: Uses ON CONFLICT DO NOTHING so it is safe to re-run (idempotent).
POSTGRES_SCAN_STATE_SEED_SQL: str = (
    "INSERT INTO scan_state (id, in_progress) VALUES (1, FALSE) "
    "ON CONFLICT DO NOTHING"
)

# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------

#: All CREATE TABLE statements in dependency order.
POSTGRES_SCHEMA_STATEMENTS: tuple[str, ...] = (
    _SCANS_DDL,
    _DOCUMENTS_DDL,
    _AUDIT_RESULTS_DDL,
    _FINDING_WORKFLOW_DDL,
    _SCAN_STATE_DDL,
)

#: All CREATE INDEX statements (safe to apply after tables exist).
POSTGRES_INDEX_STATEMENTS: tuple[str, ...] = (
    _IDX_SCANS_STATUS_ID,
    _IDX_DOCUMENTS_SCAN_ID,
    _IDX_AUDIT_RESULTS_SCAN_ID,
    _IDX_AUDIT_RESULTS_DOCUMENT_ID,
    _IDX_FINDING_WORKFLOW_STATE,
    _IDX_FINDING_WORKFLOW_DOC_SOURCE,
    _IDX_FINDING_WORKFLOW_LAST_SEEN,
    _IDX_FINDING_WORKFLOW_LAST_CHECKED,
)

#: Full schema SQL joined for inspection, display, or copy-paste use.
POSTGRES_SCHEMA_SQL: str = ";\n\n".join(
    (
        *POSTGRES_SCHEMA_STATEMENTS,
        POSTGRES_SCAN_STATE_SEED_SQL,
        *POSTGRES_INDEX_STATEMENTS,
    )
) + ";"


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def iter_postgres_schema_statements() -> tuple[str, ...]:
    """Return all schema statements in the correct application order.

    The order is:
    1. Table DDL (dependency-ordered: scans → documents → audit_results →
       finding_workflow → scan_state)
    2. Singleton scan_state seed row
    3. Index DDL

    This tuple can be executed statement-by-statement inside a transaction by
    ``PostgresStorage.connect()`` or the initial Alembic migration.
    No connection is opened here.
    """
    return (
        *POSTGRES_SCHEMA_STATEMENTS,
        POSTGRES_SCAN_STATE_SEED_SQL,
        *POSTGRES_INDEX_STATEMENTS,
    )


def render_postgres_schema_sql() -> str:
    """Return the full schema as a single semicolon-delimited SQL string.

    Useful for printing, documentation, or manual inspection.
    Does not execute anything.
    """
    return POSTGRES_SCHEMA_SQL
